#this file represents the Build stage of the pipeline where Integration tests are run and an apk is built as an output artifact
version: 0.2
phases:
  install:
    runtime-versions:
      android: 28
      java: corretto8
    commands:
      - pwd
  pre_build:
    commands:
      - echo Pre Build started on `date`
      - git clone https://github.com/flutter/flutter.git -b stable
      - export PATH="$PATH:`pwd`/flutter/bin"
      - npm install
  build:
    commands:
      - echo Integration Tests started on `date`
      #below we are trying to install an emulator in the environment
      - ${ANDROID_HOME}/tools/android list avd
      - ${ANDROID_HOME}/tools/android list target
      - ${ANDROID_HOME}/tools/android list device
      - ${ANDROID_HOME}/tools/bin/sdkmanager "platform-tools" "platforms;android-28"
      - ${ANDROID_HOME}/tools/bin/sdkmanager "system-images;android-28;google_apis;x86_64"
      - ${ANDROID_HOME}/tools/bin/sdkmanager "system-images;android-28;google_apis;x86"
      - ${ANDROID_HOME}/tools/bin/avdmanager list
      - ${ANDROID_HOME}/tools/bin/avdmanager --verbose create avd -k "system-images;android-28;google_apis;x86" --name Nexus 
      - ${ANDROID_HOME}/tools/bin/avdmanager list avd
      - ${ANDROID_HOME}/tools/bin/avdmanager create avd -n android_emulator -k "system-images;android-25;google_apis;x86"
      - echo Build started on `date`
    #Building the apk for the application
      - npx nx run app:buildApk
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
  #Path to where the apk is stored once it is built. This is then placed in the S3 bucket where it can retrieved
    - '**/app-release.apk'
  name: ReverseHand