name: CI TESTS

on:
  pull_request:
    branches: [develop]
  #push:
  #  branches: [develop]
  workflow_dispatch:
    inputs:
      testChoice:
        type: choice
        description: 'Test Type'
        required: true
        options: 
        - all
        - affected

jobs:
  test-affected-analyze:
    uses: ./.github/workflows/android.yml
    if: ${{github.event.inputs.testChoice == 'affected'}}
    with:
      test: 'affected'
      testType: 'analyze'
    
  test-affected-tests:
    uses: ./.github/workflows/android.yml
    if: ${{github.event.inputs.testChoice == 'affected'}}
    with:
      test: 'affected'
      testType: 'test'

  test-affected-build:
    uses: ./.github/workflows/android.yml
    if: ${{github.event.inputs.testChoice == 'affected'}}
    with:
      test: 'affected'
      testType: 'build'

  test-all:
    uses: ./.github/workflows/android.yml
    if: ${{github.event.inputs.testChoice == 'all' || github.event.inputs.testChoice == ''}}
    with:
      test: 'all'